name: Flutter Android Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v6

      - name: download flutter environment
        uses: subosito/flutter-action@v2.14.0

      - name: 确认 PUB_CACHE 环境变量
        run: echo ${{ env.PUB_CACHE }}
      
      - name: cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.PUB_CACHE }} 
          key: ${{ runner.os }}-pub-${{ hashFiles('pubspec.lock') }}
          restore-keys: ${{ runner.os }}-pub-
          
      - name: Install dependencies
        run: flutter pub get
        
      - name: 检查缓存目录内容
        # 列出 PUB_CACHE 目录下的文件，确认是否存在 packages
        # 如果这里没有文件，说明 pub get 写入了其他地方
        run: ls -al ${{ env.PUB_CACHE }}

      - name: Analyze project source
        run: flutter analyze

      - name: Run build
        run: flutter build web --release
